version: '3.9'

services:
  db:
    hostname: 'postgres'
    container_name: postgres_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - custom-network

  pgadmin:
    hostname: 'pgadmin4'
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - '5050:80'
    networks:
      - custom-network

  redis:
    hostname: 'redis'
    container_name: redis_container
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
