version: '3.9'

services:
  redis:
    hostname: 'redis'
    container_name: redis_container
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
